name: Deploy Latest Release

on:
  push:
    branches:
      - master

jobs:
  compress-and-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Data from main branch
        uses: actions/checkout@v2

      - name: Compress the branch content
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)
          TAR_NAME="branch-${BRANCH_NAME}.tar"
          tar -cvf $TAR_NAME .

      - name: Transfer Tarball to Server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} scp -o StrictHostKeyChecking=no $TAR_NAME ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Execute deployment script on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            ./post_front_deploy.sh
